import { createLaunch } from "@/lib/launch/engine";
import { flagDependents } from "@/lib/launch/dependencies";
import type { LaunchInput } from "@/lib/launch/types";

// Launch Workspace — the deterministic dashboard for a complete launch. Every section
// (Mission, Campaigns, Timeline, Assets, Dependencies, Publishing, Experiments,
// Performance) plus the relationship graph is rendered from a single LaunchPlan
// produced by the Launch Engine — no mock data.
const SAMPLE: LaunchInput = {
  launchType: "ai_tool_launch",
  mission: "Launch Populr, the AI CMO",
  business: { name: "Populr", audience: "seed-stage founders", oneLiner: "an AI CMO that reasons" },
  timelineDays: 28,
};

const STAGE_LABEL: Record<string, string> = { foundation: "Foundation", distribution: "Distribution", amplification: "Amplification", conversion: "Conversion" };
const SEV_CLASS: Record<string, string> = { high: "lw-sev-high", medium: "lw-sev-med", low: "lw-sev-low" };
const NAV = ["Mission", "Campaigns", "Timeline", "Assets", "Dependencies", "Publishing", "Experiments", "Performance"];

export default function LaunchWorkspace() {
  const plan = createLaunch(SAMPLE);
  const g = plan.dependencies;
  const maxDepth = g.nodes.reduce((m, n) => Math.max(m, n.depth), 0);
  // Relationship chain: Mission → first campaign → brief → its assets (origin story).
  const c0 = plan.campaigns[0];

  return (
    <section className="st-section lw">
      <header className="st-shead">
        <span className="label">Launch Workspace</span>
        <h1>{plan.mission}</h1>
        <p>
          One mission, {plan.summary.campaignCount} campaigns, {plan.summary.assetCount} assets across {plan.summary.weekCount} weeks —
          planned, sequenced and dependency-aware. Generated by the Launch Engine.
        </p>
        <nav className="lw-subnav">
          {NAV.map((s) => <a key={s} href={`#${s.toLowerCase()}`}>{s}</a>)}
        </nav>
      </header>

      {/* Mission */}
      <section id="mission" className="lw-block">
        <h2 className="lw-h2">Mission</h2>
        <div className="lw-grid2">
          <div className="lw-card">
            <div className="lw-k">Objectives</div>
            <ul className="lw-list">{plan.objectives.map((o) => <li key={o.id}>{o.statement}{o.kpi ? <span className="lw-tag">{o.kpi}</span> : null}</li>)}</ul>
          </div>
          <div className="lw-card">
            <div className="lw-k">KPIs</div>
            <ul className="lw-list">{plan.kpis.map((k, i) => <li key={i}>{k.metric}: <b>{k.target}</b> <span className="lw-muted">/ {k.timeframe}</span></li>)}</ul>
            {plan.risks.length > 0 && <>
              <div className="lw-k" style={{ marginTop: 14 }}>Risks</div>
              <ul className="lw-list">{plan.risks.map((r) => <li key={r.id}><span className={"lw-dot " + SEV_CLASS[r.level]} />{r.description}</li>)}</ul>
            </>}
          </div>
        </div>
      </section>

      {/* Campaigns */}
      <section id="campaigns" className="lw-block">
        <h2 className="lw-h2">Campaigns</h2>
        <div className="lw-cards">
          {plan.campaigns.map((c) => (
            <div key={c.id} className="lw-card">
              <div className="lw-card-h">{c.title}</div>
              <div className="lw-meta">{STAGE_LABEL[c.phase]} · goal {c.goal.replace(/_/g, " ")} · P{c.priority}</div>
              <div className="lw-chips">{c.channels.map((ch) => <span key={ch} className="lw-chip">{ch}</span>)}</div>
              <div className="lw-meta">{c.assetPlan.summary.total} assets · {Math.round(c.budgetShare * 100)}% of budget</div>
            </div>
          ))}
        </div>
      </section>

      {/* Timeline */}
      <section id="timeline" className="lw-block">
        <h2 className="lw-h2">Timeline</h2>
        <div className="lw-timeline">
          {plan.weeks.map((w) => (
            <div key={w.week} className="lw-week">
              <div className="lw-week-h">{w.label}<span className="lw-week-phase">{STAGE_LABEL[w.phase]}</span></div>
              <ul className="lw-week-items">
                {w.items.length === 0 ? <li className="lw-muted">—</li> :
                  w.items.map((it) => <li key={it.assetKey}>{it.quantity > 1 ? `${it.quantity}× ` : ""}{it.label}<span className="lw-week-ch">{it.channel}</span></li>)}
              </ul>
            </div>
          ))}
        </div>
      </section>

      {/* Assets */}
      <section id="assets" className="lw-block">
        <h2 className="lw-h2">Assets</h2>
        <div className="lw-cards">
          {plan.campaigns.map((c) => (
            <div key={c.id} className="lw-card">
              <div className="lw-card-h">{c.title}</div>
              <div className="lw-chips">{c.assetPlan.assets.map((a) => <span key={a.key} className="lw-chip">{a.quantity > 1 ? `${a.quantity}× ` : ""}{a.label}</span>)}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Dependencies */}
      <section id="dependencies" className="lw-block">
        <h2 className="lw-h2">Dependencies</h2>
        <p className="lw-muted lw-sub">Change an upstream asset and every downstream asset is flagged for review.</p>
        <div className="lw-dep">
          {Array.from({ length: maxDepth + 1 }, (_, d) => (
            <div key={d} className="lw-dep-col">
              <div className="lw-dep-h">Depth {d}</div>
              {g.nodes.filter((n) => n.depth === d).map((n) => {
                const flagged = flagDependents(g, n.key).length;
                return (
                  <div key={n.key} className="lw-dep-node" title={n.dependsOn.length ? `from ${n.dependsOn.join(", ")}` : "root"}>
                    {n.label}
                    {flagged > 0 && <span className="lw-dep-count">{flagged}↓</span>}
                  </div>
                );
              })}
            </div>
          ))}
        </div>
      </section>

      {/* Publishing */}
      <section id="publishing" className="lw-block">
        <h2 className="lw-h2">Publishing</h2>
        <div className="lw-pipe">
          {["draft", "creative_review", "approval", "scheduled", "publishing", "published", "measured", "archived"].map((s, i) => (
            <span key={s} className="lw-pipe-stage">{s.replace(/_/g, " ")}{i < 7 ? <span className="lw-pipe-arrow">→</span> : null}</span>
          ))}
        </div>
        <div className="lw-cards">
          {plan.publishingSchedule.slice(0, 9).map((s) => (
            <div key={s.assetKey} className="lw-card lw-slot">
              <div className="lw-slot-day">Day {s.dayOffset}</div>
              <div className="lw-card-h">{s.kind.replace(/_/g, " ")}</div>
              <div className="lw-meta">{s.channel} · week {s.week} · <span className="lw-stage">{s.stage}</span></div>
            </div>
          ))}
        </div>
      </section>

      {/* Experiments */}
      <section id="experiments" className="lw-block">
        <h2 className="lw-h2">Experiments</h2>
        <div className="lw-cards">
          {plan.experiments.map((e) => (
            <div key={e.id} className="lw-card">
              <div className="lw-card-h">{e.type.replace(/_/g, " ")}</div>
              <p className="lw-hyp">{e.hypothesis}</p>
              <div className="lw-chips">{e.variants.map((v) => <span key={v.id} className="lw-chip">{v.label}</span>)}</div>
              <div className="lw-meta">{e.winnerVariantId ? `winner: ${e.winnerVariantId}` : "awaiting results"}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Performance */}
      <section id="performance" className="lw-block">
        <h2 className="lw-h2">Performance</h2>
        <div className="lw-cards">
          {plan.kpis.map((k, i) => (
            <div key={i} className="lw-card lw-perf">
              <div className="lw-perf-metric">{k.metric}</div>
              <div className="lw-perf-target">{k.target}</div>
              <div className="lw-muted">{k.timeframe} · measured post-launch</div>
            </div>
          ))}
        </div>
      </section>

      {/* Relationship graph */}
      <section className="lw-block">
        <h2 className="lw-h2">Where every asset comes from</h2>
        <div className="lw-rel">
          <span className="lw-rel-node lw-rel-root">Mission</span><span className="lw-rel-arrow">→</span>
          <span className="lw-rel-node">Campaign: {c0.title.split("—")[1]?.trim() || c0.goal}</span><span className="lw-rel-arrow">→</span>
          <span className="lw-rel-node">Creative Brief</span><span className="lw-rel-arrow">→</span>
          {c0.assetPlan.assets.slice(0, 6).map((a) => (
            <span key={a.key} className="lw-rel-node lw-rel-asset">{a.label}</span>
          ))}
        </div>
      </section>
    </section>
  );
}
